/// Flutter icons ControlIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ControlIcons
///      fonts:
///       - asset: fonts/ControlIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ControlIcons {
  ControlIcons._();

  static const _kFontFam = 'ControlIcons';
  static const String? _kFontPkg = null;

  static const IconData cupWater =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulbOn =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprinklerFire =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
